### YamlMime:UniversalReference
ms.openlocfilehash: 777051058935475aebf2055932882ec0cd21fea9
ms.sourcegitcommit: efa2d98deffe8a0d41a8d63f9f07aa720862e6ab
ms.translationtype: MT
ms.contentlocale: it-IT
ms.lasthandoff: 12/13/2018
ms.locfileid: "52135176"
items:
- uid: azure-servicefabric.TestErrorChaosEvent
  name: TestErrorChaosEvent
  fullName: TestErrorChaosEvent
  children:
  - azure-servicefabric.TestErrorChaosEvent.reason
  langs:
  - typeScript
  type: interface
  summary: >-
    Descrive un evento di Chaos viene generato quando si verifica un evento imprevisto nel motore di Chaos.

    Ad esempio, a causa dello snapshot di cluster in corso incoerente, durante un'entità di generare un errore, Chaos individuato che l'entità è stata già verificati errori, che potrebbe essere un evento imprevisto.
  extends:
    name: azure-servicefabric.ChaosEvent
  package: azure-servicefabric
- uid: azure-servicefabric.TestErrorChaosEvent.reason
  name: reason
  fullName: reason
  children: []
  langs:
  - typeScript
  type: property
  summary: Descrive il motivo per cui è stato generato TestErrorChaosEvent. Ad esempio, Chaos tenta di una partizione di errore, ma individua che la partizione non è più a tolleranza di errore, quindi un TestErrorEvent generato con il motivo che informa che la partizione non è a tolleranza di errore.
  optional: true
  syntax:
    content: 'reason?: string'
    return:
      type:
      - string
  package: azure-servicefabric
references:
- uid: azure-servicefabric.ChaosEvent
  name: ChaosEvent
  spec.typeScript:
  - name: ChaosEvent
    fullName: ChaosEvent
    uid: azure-servicefabric.ChaosEvent
